# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RACD Simulation Model
#'
#' Run the simulation
#'
#' @param tMax length of simulation in days
#' @param theta named list of parameters (see \code{\link{RACD_Parameters}} for details)
#' @param human list of human parameters (see \code{\link{RACD_Setup}} for details)
#' @param house list of house parameters (see \code{\link{RACD_Setup}} for details)
#' @param seed seed for prng class
#' @param outfile path to .csv file for logging state transition events
#'
#' @examples
#' \dontrun{
#' library(RACD)
#' library(tidyverse)
#' library(spatstat)
#' xy_h <- rpoispp(lambda = 100,win = owin(c(0,1),c(0,1)))
#' xy_b <- rpoispp(lambda = 100,win = owin(c(0,1),c(0,1)))
#' theta <- RACD_Parameters()
#' init <- RACD_Setup(as.matrix.ppx(xy_h),as.matrix.ppx(xy_b),theta)
#' outfile = "/Users/slwu89/Desktop/log_trans.csv"
#' RACD_Simulation(365,theta,init$humans,init$houses,123,outfile)
#' state = RACD_StateVector(outfile)
#' state %>% as.tibble %>% gather(state,value,-time) %>% ggplot(aes(x=time,y=value,color=state)) + geom_line() + theme_bw()
#' }
#'
#' @export
RACD_Simulation <- function(tMax, theta, human, house, seed) {
    .Call('_RACD_RACD_Simulation', PACKAGE = 'RACD', tMax, theta, human, house, seed)
}

