# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' RACD Simulation Model
#'
#' Run the simulation
#'
#' @param tMax length of simulation in days
#' @param theta named list of parameters (see \code{\link[RACDaux]{RACD_Parameters}} for details)
#' @param human list of human parameters (see \code{\link[RACDaux]{RACD_Setup}} for details)
#' @param house list of house parameters (see \code{\link[RACDaux]{RACD_Setup}} for details)
#' @param seed seed for prng class
#' @param out_trans path to .csv file for logging state transition events
#'
#' @examples
#' theta = RACDaux::RACD_Parameters()
#' init = RACDaux::RACD_Setup(theta)
#' \dontrun{
#'   library(tidyverse)
#'   outfile = "/Users/slwu89/Desktop/log_trans.csv"
#'   RACD_Simulation(365,theta,init$humans,init$houses,123,outfile)
#'   state = RACDaux::RACD_StateVector(outfile)
#'   state %>% as.tibble %>% gather(state,value,-time) %>% ggplot(aes(x=time,y=value,color=state)) + geom_line() + theme_bw()
#' }
#'
#' @export
RACD_Simulation <- function(tMax, theta, human, house, seed, out_trans) {
    invisible(.Call('_RACD_RACD_Simulation', PACKAGE = 'RACD', tMax, theta, human, house, seed, out_trans))
}

