# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Unit Test: RACD_Parameters
#'
#' @param theta output of \code{\link[RACDaux]{RACD_Parameters}}
#'
#' @export
test_parameters <- function(theta) {
    invisible(.Call('_RACD_test_parameters', PACKAGE = 'RACD', theta))
}

#' Unit Test: test_human
#'
#' @param theta output of \code{\link[RACDaux]{RACD_Parameters}}
#'
#' @export
test_human_parameters <- function(theta) {
    invisible(.Call('_RACD_test_human_parameters', PACKAGE = 'RACD', theta))
}

#' Unit Test: prng
#'
#' test the composition prng class within the parameters singleton
#'
#' @export
test_prng <- function(seed) {
    invisible(.Call('_RACD_test_prng', PACKAGE = 'RACD', seed))
}

#' Unit Test: house
#'
#' test putting a human in a house and calling some basic actions
#'
#' @export
test_house <- function(theta, seed) {
    invisible(.Call('_RACD_test_house', PACKAGE = 'RACD', theta, seed))
}

