// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_parameters
void test_parameters();
RcppExport SEXP _RACD_test_parameters() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test_parameters();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RACD_test_parameters", (DL_FUNC) &_RACD_test_parameters, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RACD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
