// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hi
void hi();
RcppExport SEXP _RACD_hi() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    hi();
    return R_NilValue;
END_RCPP
}
// test_parameters
void test_parameters(const Rcpp::NumericVector& theta);
RcppExport SEXP _RACD_test_parameters(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    test_parameters(theta);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RACD_hi", (DL_FUNC) &_RACD_hi, 0},
    {"_RACD_test_parameters", (DL_FUNC) &_RACD_test_parameters, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RACD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
